# Generated by Django 4.2.7 on 2023-12-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_created_date_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
