# Generated by Django 4.2.7 on 2023-12-26 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_quickadd_category_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='İsim')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Telefon Numarası')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Borç')),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mal Fiyatı')),
            ],
            options={
                'verbose_name_plural': 'Satış Yapan Kişiler',
            },
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
