# Generated by Django 4.2.7 on 2024-01-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sales_is_payment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
