# Generated by Django 4.2.7 on 2024-01-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_quickadd_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
